const translations = {
    en: {
        nav_about: "About",
        nav_skills: "Skills",
        nav_projects: "Projects",
        nav_contact: "Contact",
        status_available: "Available for Work",
        hero_title_1: "Building Intelligent",
        hero_title_2: "Automations",
        hero_subtitle: "I am an AI & Automation Architect specializing in n8n, Python, and Multi-modal RAG systems. I help businesses save thousands of hours by replacing manual work with smart pipelines.",
        btn_view_work: "View My Work",
        btn_contact: "Contact Me",
        projects_title: "Featured Architecture Cases",
        projects_subtitle: "Explore how I solved complex business problems using advanced APIs, LLMs, and custom scripts.",
        about_title: "About Me",
        about_text: "I am an AI Automation Expert with a strong background in logistics and dispatching. This experience taught me to work under high responsibility and understand the critical importance of stability in every process link. I specialize in building intelligent systems that automate client communication, document processing, and data analysis. I love finding creative solutions to complex problems, building stable scenarios in n8n, Make.com, and Zapier, and implementing AI to free teams from routine tasks.",
        contact_title: "Let's Connect",
        contact_email: "Email",
        contact_phone: "Phone",
        contact_agent: "My AI Agent",
        contact_messengers: "Or message me directly on:",
        methodology_title: "My Architecture Methodology",
        stage_1_title: "Stage 1: Problem",
        stage_1_text: "Identifying bottlenecks, manual chaos, and business pain points.",
        stage_2_title: "Stage 2: Analysis",
        stage_2_text: "Deep dive into data flows, API capabilities, and AI integration points.",
        stage_3_title: "Stage 3: Solution",
        stage_3_text: "Designing the perfect automation blueprint and selecting the right tools.",
        stage_4_title: "Stage 4: Implementation",
        stage_4_text: "Building, testing, and deploying the stable automated pipeline.",
        stage_5_title: "Stage 5: Result",
        stage_5_text: "Profitability, time saved, and client satisfaction.",
        skills_title: "Tech Stack & Skills",
        skills_subtitle: "Tools and technologies I use to build scalable automation architectures."
    },
    ua: {
        nav_about: "Про мене",
        nav_skills: "Навички",
        nav_projects: "Проєкти",
        nav_contact: "Контакти",
        status_available: "Відкритий до пропозицій",
        hero_title_1: "Створюю Інтелектуальні",
        hero_title_2: "Автоматизації",
        hero_subtitle: "Я AI & Automation Architect. Спеціалізуюсь на n8n, Python та Multi-modal RAG системах. Допомагаю бізнесу економити тисячі годин, замінюючи ручну працю на розумні пайплайни.",
        btn_view_work: "Мої роботи",
        btn_contact: "Зв'язатися",
        projects_title: "Архітектурні Кейси",
        projects_subtitle: "Дізнайтеся, як я вирішував складні бізнес-задачі за допомогою сучасних API, LLM та скриптів.",
        about_title: "Про мене",
        about_text: "Я AI Automation Expert із фокусом на побудову безперебійних інтеграцій та масштабування бізнесу за допомогою No-code інструментів. Маючи багаторічний досвід у логістиці, я звик працювати в режимі високої відповідальності та розумію критичну важливість стабільності процесу. Спеціалізуюся на створенні інтелектуальних систем, які автоматизують комунікацію з клієнтами та обробку документів. Обожнюю знаходити нестандартні рішення для складних задач, працюю з API та створюю стабільні сценарії в n8n, Make.com та Zapier.",
        contact_title: "Мої контакти",
        contact_email: "Електронна пошта",
        contact_phone: "Телефон",
        contact_agent: "Мій AI Асистент",
        contact_messengers: "Або напишіть мені безпосередньо у:",
        methodology_title: "Моя Архітектурна Методологія",
        stage_1_title: "Етап 1: Проблема",
        stage_1_text: "Виявлення вузьких місць, ручного хаосу та болей бізнесу.",
        stage_2_title: "Етап 2: Аналіз",
        stage_2_text: "Глибоке занурення в потоки даних, можливості API та точки інтеграції AI.",
        stage_3_title: "Етап 3: Рішення",
        stage_3_text: "Проєктування ідеального плану автоматизації та вибір правильних інструментів.",
        stage_4_title: "Етап 4: Впровадження",
        stage_4_text: "Розробка, тестування та розгортання стабільного автоматизованого пайплайну.",
        stage_5_title: "Етап 5: Результат",
        stage_5_text: "Прибутковість, зекономлений час та задоволеність клієнтів.",
        skills_title: "Технологічний Стек",
        skills_subtitle: "Інструменти та технології, які я використовую для створення масштабованих архітектур."
    }
};

const projects = [

    {
        id: "proj_0",
        image: "assets/ai_content.png",
        title: {
            en: `Autonomous AI Content Ecosystem`,
            ua: `Autonomous AI Content Ecosystem`
        },
        tags: ['n8n', 'Baserow', 'Gemini', 'Vertex AI', 'LinkedIn'],
        summary: {
            en: `Systematic maintenance of social networks (LinkedIn, Facebook) for experts or B2B companies requires a huge amount of time: searching for topics, collecting facts, writing texts fo...`,
            ua: `Системне ведення соціальних мереж (LinkedIn, Facebook) для експертів чи B2B-компаній вимагає колосальних витрат часу: пошук тем, збір фактажу, написання текстів під різні формати т...`
        },
        content: {
            en: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. The business problem (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Systematic maintenance of social networks (LinkedIn, Facebook) for experts or B2B companies requires a huge amount of time: searching for topics, collecting facts, writing texts for different formats and selecting illustrations. Hiring an SMM department is expensive, and writing yourself is not enough time. The task was to create a system that would work for months on full autopilot, generating not typical "artificial" text, but deep, factual content with the right logic to warm up the audience.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. The Solution and Architecture (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">I designed and implemented an autonomous "content factory" at<strong class="text-white">n8n</strong>that independently conducts research, writes posts and publishes them according to a complex content plan.<br>-<strong class="text-white">Data Management (Baserow):</strong>As an architectural solution, I chose Baserow over Airtable to get around the hard limits of free API requests. The database stores global topics for months ahead and a matrix of AI settings (Tone of Voice, Temperature, character limits, hashtags).<br>-<strong class="text-white">Deep Research (Firecrawl):</strong>Before writing a post, the script takes a given topic and through Firecrawl scans the Internet to collect relevant data. Thus, AI (Gemini) relies on fresh facts and not on its own hallucinations.<br>-<strong class="text-white">Logic of warm-up by days of the week:</strong>The script distinguishes the context of the publication. On Monday, a post is generated about<strong class="text-white">"pains"</strong>of the business (provocative tone), on Wednesday -<strong class="text-white">analytics and solutions</strong>(historical/intelligent tone), on Friday -<strong class="text-white">opportunities</strong>(inspirational tone). The texts are also dynamically adapted to the specifics of LinkedIn and Facebook.<br>-<strong class="text-white">Visual (Vertex AI):</strong>For each post, the system automatically generates a unique image through Vertex AI, automatically downloads it and attaches it to the post.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Tech Stack</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Orchestration:</strong>n8n (complex routing, Switch/Filter nodes, HTTP Requests)<br>-<strong class="text-white">Database:</strong>Baserow (Relational Database)<br>-<strong class="text-white">AI Core:</strong>Gemini Flash (Text), Vertex AI Imagen (Images)<br>-<strong class="text-white">Data Collection:</strong>Firecrawl (Web Scraping & Search)<br>-<strong class="text-white">Integrations:</strong>LinkedIn API, Facebook Graph API, Telegram API (for notifications about successful posting)</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Business result (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Absolute autonomy:</strong>It is enough to spend 10 minutes once every few months to enter 5-7 topics in the table. Next, the system automatically maintains 2 social networks 3 days a week without any intervention.<br>-<strong class="text-white">High quality:</strong>Thanks to deep research and fine-tuning of the temperature (Temperature) and tone (Tone of Voice) in the database, the content looks expert and natural.<br>-<strong class="text-white">Zero production costs:</strong>The use of custom integrations and Google Cloud grant credits (Vertex AI) made it possible to reduce the cost of producing unique content (text + images) to almost zero, replacing the work of a full-fledged SMM specialist.<br><br><br>---</div>
`,
            ua: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. Проблема бізнесу (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Системне ведення соціальних мереж (LinkedIn, Facebook) для експертів чи B2B-компаній вимагає колосальних витрат часу: пошук тем, збір фактажу, написання текстів під різні формати та підбір ілюстрацій. Наймати SMM-відділ — дорого, а писати самому — не вистачає часу. Завдання полягало у створенні системи, яка б місяцями працювала на повному автопілоті, генеруючи не типовий "штучний" текст, а глибокий, фактологічний контент із правильною логікою прогріву аудиторії.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. Рішення та Архітектура (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Я розробив і впровадив автономний "завод контенту" в <strong class="text-white">n8n</strong>, який самостійно проводить дослідження, пише пости та публікує їх за складним контент-планом.<br><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Керування даними (Baserow):</strong> Як архітектурне рішення я обрав Baserow замість Airtable, щоб обійти жорсткі ліміти безкоштовних API-запитів. У базі зберігаються глобальні теми на місяці вперед та матриця налаштувань ШІ (Tone of Voice, Temperature, ліміти знаків, хештеги).</li><br><li><strong class="text-white">Deep Research (Firecrawl):</strong> Перед тим як писати пост, сценарій бере задану тему і через Firecrawl сканує інтернет для збору актуальних даних. Таким чином, ШІ (Gemini) спирається на свіжі факти, а не на власні галюцинації.</li><br><li><strong class="text-white">Логіка прогріву по днях тижня:</strong> Сценарій розрізняє контекст публікації. У понеділок генерується пост про <strong class="text-white">"болі"</strong> бізнесу (провокаційний тон), у середу — <strong class="text-white">аналітика та вирішення</strong> (історичний/розумний тон), у п'ятницю — <strong class="text-white">можливості</strong> (надихаючий тон). Тексти також динамічно адаптуються під специфіку LinkedIn та Facebook.</li><br><li><strong class="text-white">Візуал (Vertex AI):</strong> Для кожного посту система автоматично генерує унікальне зображення через Vertex AI, самостійно завантажує його і прикріплює до публікації.</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Технічний стек (Tech Stack)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Оркестрація:</strong> n8n (складна маршрутизація, Switch/Filter ноди, HTTP Requests)</li><br><li><strong class="text-white">База даних:</strong> Baserow (Relational Database)</li><br><li><strong class="text-white">ШІ-ядро:</strong> Gemini Flash (Text), Vertex AI Imagen (Images)</li><br><li><strong class="text-white">Збір даних:</strong> Firecrawl (Web Scraping & Search)</li><br><li><strong class="text-white">Інтеграції:</strong> LinkedIn API, Facebook Graph API, Telegram API (для сповіщень про успішний постинг)</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Бізнес-результат (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Абсолютна автономність:</strong> Достатньо раз на кілька місяців витратити 10 хвилин, щоб вписати 5-7 тем у таблицю. Далі система автоматично веде 2 соцмережі 3 дні на тиждень без жодного втручання.</li><br><li><strong class="text-white">Висока якість:</strong> Завдяки глибокому ресерчу та тонкому налаштуванню температури (Temperature) і тону (Tone of Voice) у базі даних, контент виглядає експертно та природно.</li><br><li><strong class="text-white">Нульові витрати на продакшн:</strong> Використання кастомних інтеграцій та грантових кредитів Google Cloud (Vertex AI) дозволило звести вартість виробництва унікального контенту (текст + зображення) практично до нуля, замінивши роботу повноцінного SMM-спеціаліста.</li><br></ul><br><br>---</div>
`
        }
    },
    {
        id: "proj_1",
        image: "assets/content_v2.png",
        title: {
            en: `Autonomous AI Content Ecosystem`,
            ua: `Autonomous AI Content Ecosystem`
        },
        tags: ['n8n', 'Baserow', 'Gemini', 'Vertex AI', 'LinkedIn'],
        summary: {
            en: `Systematic maintenance of social networks (LinkedIn, Facebook) for experts or B2B companies requires a huge amount of time: searching for topics, collecting facts, writing texts fo...`,
            ua: `Системне ведення соціальних мереж (LinkedIn, Facebook) для експертів чи B2B-компаній вимагає колосальних витрат часу: пошук тем, збір фактажу, написання текстів під різні формати т...`
        },
        content: {
            en: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. The business problem (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Systematic maintenance of social networks (LinkedIn, Facebook) for experts or B2B companies requires a huge amount of time: searching for topics, collecting facts, writing texts for different formats and selecting illustrations. Hiring an SMM department is expensive, and writing yourself is not enough time. The task was to create a system that would work for months on full autopilot, generating not typical "artificial" text, but deep, factual content with the right logic to warm up the audience.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. Evolution of architecture (Architecture Pivot)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">This project went through two stages of development, which made it possible to find the perfect balance between control and cost:<br>-<strong class="text-white">V1 (Human-in-the-loop):</strong>Initially, the system was based on the connection of<strong class="text-white">Airtable + Softr</strong>. The script generated content, and through a user-friendly interface in Softr (Dashboard), a person could manually check the texts by pressing the "Send for publication" or "Regenerate" buttons. However, the system quickly reached the limit of 1000 API requests of the free Airtable tariff.<br>-<strong class="text-white">V2 (Fully Autonomous & Cost-Optimized):</strong>Instead of switching to expensive paid plans, I completely changed the architecture. Airtable has been replaced by<strong class="text-white">Baserow</strong>(no limits). The generation process was so polished with prompts that the need for manual verification through Softr disappeared — the system became 100% autonomous.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. The Solution and Pipeline (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Today it is a completely autonomous "content factory" in<strong class="text-white">n8n</strong>:<br>-<strong class="text-white">Data management (Baserow):</strong>Global topics for months ahead and a matrix of AI settings (Tone of Voice, Temperature, character limits, hashtags) are stored in the database.<br>-<strong class="text-white">Deep Research (Firecrawl):</strong>Before writing a post, the script takes a given topic and through Firecrawl scans the Internet to collect relevant data. Thus, AI (Gemini) relies on fresh facts and not on its own hallucinations.<br>-<strong class="text-white">Logic of warm-up by days of the week:</strong>The script distinguishes the context of the publication. On Monday, a post is generated about<strong class="text-white">"pains"</strong>of the business (provocative tone), on Wednesday -<strong class="text-white">analytics and solutions</strong>(historical/intelligent tone), on Friday -<strong class="text-white">opportunities</strong>(inspirational tone). The texts are also dynamically adapted to the specifics of LinkedIn and Facebook.<br>-<strong class="text-white">Visual (Vertex AI) and Storage (Google Drive):</strong>For each post, a unique image is automatically generated by Vertex AI, which is stored on Google Drive before the final publication.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Tech Stack</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Orchestration:</strong>n8n (complex routing, Switch/Filter nodes, parallel branches)<br>-<strong class="text-white">Database and Interfaces:</strong>Baserow (V2), Airtable + Softr (V1)<br>-<strong class="text-white">AI Core:</strong>Gemini Flash (Text), Vertex AI Imagen (Images)<br>-<strong class="text-white">Data Collection:</strong>Firecrawl (Web Scraping & Search)<br>-<strong class="text-white">Integrations:</strong>Google Drive API, LinkedIn API, Facebook Graph API, Telegram API (for notifications about successful posting)</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">5. Business result (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Absolute autonomy:</strong>It is enough to spend 10 minutes once every few months to enter 5-7 topics in the table. Next, the system automatically maintains 2 social networks 3 days a week without any intervention.<br>-<strong class="text-white">Total savings:</strong>Rejection of Airtable/Softr in favor of Baserow, as well as the use of Google Cloud (Vertex AI) grant credits allowed to reduce the cost of producing unique content to almost zero.<br>-<strong class="text-white">Scalability:</strong>The architecture easily allows you to add new social networks (like Instagram or X) or new post days just by adding a new branch in n8n.<br><br><br>---</div>
`,
            ua: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. Проблема бізнесу (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Системне ведення соціальних мереж (LinkedIn, Facebook) для експертів чи B2B-компаній вимагає колосальних витрат часу: пошук тем, збір фактажу, написання текстів під різні формати та підбір ілюстрацій. Наймати SMM-відділ — дорого, а писати самому — не вистачає часу. Завдання полягало у створенні системи, яка б місяцями працювала на повному автопілоті, генеруючи не типовий "штучний" текст, а глибокий, фактологічний контент із правильною логікою прогріву аудиторії.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. Еволюція архітектури (Architecture Pivot)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Цей проєкт пройшов дві стадії розвитку, що дозволило знайти ідеальний баланс між контролем та вартістю:<br><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">V1 (Human-in-the-loop):</strong> Спочатку система базувалася на зв'язці <strong class="text-white">Airtable + Softr</strong>. Сценарій генерував контент, і через зручний інтерфейс у Softr (Dashboard) людина могла вручну перевіряти тексти, натискаючи кнопки "Відправити на публікацію" або "Перегенерувати". Проте система швидко вперлася в ліміт 1000 API-запитів безкоштовного тарифу Airtable.</li><br><li><strong class="text-white">V2 (Fully Autonomous & Cost-Optimized):</strong> Замість переходу на дорогі платні тарифи, я повністю змінив архітектуру. Airtable був замінений на <strong class="text-white">Baserow</strong> (без лімітів). Процес генерації був настільки відшліфований промптами, що необхідність у ручній перевірці через Softr відпала — система стала на 100% автономною.</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Рішення та Пайплайн (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Сьогодні це повністю автономний "завод контенту" в <strong class="text-white">n8n</strong>:<br><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Керування даними (Baserow):</strong> У базі зберігаються глобальні теми на місяці вперед та матриця налаштувань ШІ (Tone of Voice, Temperature, ліміти знаків, хештеги).</li><br><li><strong class="text-white">Deep Research (Firecrawl):</strong> Перед тим як писати пост, сценарій бере задану тему і через Firecrawl сканує інтернет для збору актуальних даних. Таким чином, ШІ (Gemini) спирається на свіжі факти, а не на власні галюцинації.</li><br><li><strong class="text-white">Логіка прогріву по днях тижня:</strong> Сценарій розрізняє контекст публікації. У понеділок генерується пост про <strong class="text-white">"болі"</strong> бізнесу (провокаційний тон), у середу — <strong class="text-white">аналітика та вирішення</strong> (історичний/розумний тон), у п'ятницю — <strong class="text-white">можливості</strong> (надихаючий тон). Тексти також динамічно адаптуються під специфіку LinkedIn та Facebook.</li><br><li><strong class="text-white">Візуал (Vertex AI) та Сховище (Google Drive):</strong> Для кожного посту автоматично генерується унікальне зображення через Vertex AI, яке зберігається на Google Drive перед фінальною публікацією.</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Технічний стек (Tech Stack)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Оркестрація:</strong> n8n (складна маршрутизація, Switch/Filter ноди, паралельні гілки)</li><br><li><strong class="text-white">База даних та Інтерфейси:</strong> Baserow (V2), Airtable + Softr (V1)</li><br><li><strong class="text-white">ШІ-ядро:</strong> Gemini Flash (Text), Vertex AI Imagen (Images)</li><br><li><strong class="text-white">Збір даних:</strong> Firecrawl (Web Scraping & Search)</li><br><li><strong class="text-white">Інтеграції:</strong> Google Drive API, LinkedIn API, Facebook Graph API, Telegram API (для сповіщень про успішний постинг)</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">5. Бізнес-результат (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Абсолютна автономність:</strong> Достатньо раз на кілька місяців витратити 10 хвилин, щоб вписати 5-7 тем у таблицю. Далі система автоматично веде 2 соцмережі 3 дні на тиждень без жодного втручання.</li><br><li><strong class="text-white">Тотальна економія:</strong> Відмова від Airtable/Softr на користь Baserow, а також використання грантових кредитів Google Cloud (Vertex AI) дозволили звести вартість виробництва унікального контенту практично до нуля.</li><br><li><strong class="text-white">Масштабованість:</strong> Архітектура легко дозволяє додати нові соціальні мережі (наприклад, Instagram чи X) або нові дні публікації просто додавши нову гілку в n8n.</li><br></ul><br><br>---</div>
`
        }
    },
    {
        id: "proj_2",
        image: "assets/ecommerce_banner.png",
        title: {
            en: `E-Commerce Creative Factory (Telegram to Banner)`,
            ua: `E-Commerce Creative Factory (Telegram to Banner)`
        },
        tags: ['n8n', 'Gemini', 'Telegram', 'Cloudinary'],
        summary: {
            en: `The owner of an online store spent hours on a routine creation of advertising posts for social networks. To make one post about "Promotion" or "Product of the day", it was necessar...`,
            ua: `Власник інтернет-магазину витрачав години на рутинне створення рекламних постів для соцмереж. Щоб зробити один пост про "Акцію" або "Товар дня", потрібно було: зайти на сайт, скопі...`
        },
        content: {
            en: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. The business problem (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">The owner of an online store spent hours on a routine creation of advertising posts for social networks. To make one post about "Promotion" or "Product of the day", it was necessary to: go to the site, copy the characteristics, upload a photo, open Photoshop or Canva, manually overlay the text with discounts, and then also come up with the selling text. The client wanted to reduce the creation of a full-fledged promotional creative to one message in the messenger.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. The Solution and Architecture (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">I developed a full-fledged Telegram application (based on an extremely complex script in<strong class="text-white">n8n</strong>), which turns a link from a site into a ready-made advertising banner in 90 seconds.<br><br>-<strong class="text-white">Interaction (UI):</strong>Telegram bot has a custom button menu. The customer chooses a category (e.g. "🔥 Sale" or "⚡️ Product of the Day") and simply sends a link to his product.<br>-<strong class="text-white">Extraction and Copywriting:</strong>The system parses the product page (name, old/new prices, characteristics, photo). Next,<strong class="text-white">Google Gemini</strong>is included in the work, which writes the selling text of the post, using the given Tone of Voice and adding relevant emojis.<br>-<strong class="text-white">Banner Generation (Visual Automation):</strong>The most difficult technical challenge was to overlay the generated text and prices on the image so that it looks professional and "expensive". Basic tools (like layering via Cloudinary) gave a terrible visual result. I solved this problem by integrating the API of the service<strong class="text-white">Nano Banano Pro</strong>, which allowed to dynamically render complex design templates with beautiful typography, discount badges and crossed out prices on the fly.<br>-<strong class="text-white">Distribution:</strong>The bot returns the perfect banner along with the text. The owner can click a button to instantly post to their channel or set a time for delayed posting.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Tech Stack</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Orchestration:</strong>n8n (Scale pipeline with dozens of parallel branches, Switch routers and Webhooks)<br>-<strong class="text-white">Interface:</strong>Telegram Bot API (Custom Keyboards, Inline Buttons)<br>-<strong class="text-white">AI-Models:</strong>Google Gemini (data analysis from the site and text generation)<br>-<strong class="text-white">Dynamic Design API:</strong>Nano Banano Pro (automatic generation of complex banners)</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Business result (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Lightning speed:</strong>The time to create a professional promo post has been reduced from 20-30 minutes of manual work to<strong class="text-white">1.5 minutes</strong>background waiting.<br>-<strong class="text-white">Replacement of the marketing department:</strong>The system completely replaced the work of the SMM manager and graphic designer. A business owner can run sales right from their smartphone while standing in traffic.<br>-<strong class="text-white">Advanced Architecture:</strong>The screenshot of the tree of this scenario in n8n clearly proves the ability to build an Enterprise-level architecture that does not "fall" during the execution of complex branched processes.<br><br><br>---</div>
`,
            ua: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. Проблема бізнесу (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Власник інтернет-магазину витрачав години на рутинне створення рекламних постів для соцмереж. Щоб зробити один пост про "Акцію" або "Товар дня", потрібно було: зайти на сайт, скопіювати характеристики, завантажити фото, відкрити Photoshop чи Canva, вручну накласти текст зі знижками, а потім ще й придумати продаючий текст. Клієнт хотів звести створення повноцінного промо-креативу до одного повідомлення в месенджері.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. Рішення та Архітектура (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Я розробив повноцінний Telegram-додаток (на базі надскладного сценарію в <strong class="text-white">n8n</strong>), який перетворює посилання з сайту на готовий рекламний банер за 90 секунд.<br><br><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Взаємодія (UI):</strong> У Telegram-боті налаштовано кастомне меню кнопок. Клієнт обирає рубрику (напр., "🔥 Розпродаж" або "⚡️ Товар дня") і просто відправляє лінк на свій товар.</li><br><li><strong class="text-white">Екстракція та Копірайтинг:</strong> Система парсить сторінку товару (назву, старі/нові ціни, характеристики, фото). Далі в роботу включається <strong class="text-white">Google Gemini</strong>, який пише продаючий текст посту, використовуючи заданий Tone of Voice та додаючи релевантні емодзі.</li><br><li><strong class="text-white">Генерація Банера (Visual Automation):</strong> Найскладнішим технічним викликом було накласти згенерований текст та ціни на картинку так, щоб це виглядало професійно і "дорого". Базові інструменти (на кшталт накладання шарів через Cloudinary) давали жахливий візуальний результат. Я вирішив цю проблему, інтегрувавши API сервісу <strong class="text-white">Nano Banano Pro</strong>, який дозволив динамічно рендерити складні дизайн-шаблони з красивою типографікою, бейджами знижок та перекресленими цінами на льоту.</li><br><li><strong class="text-white">Дистрибуція:</strong> Бот повертає ідеальний банер разом з текстом. Власник може натиснути кнопку для миттєвої публікації у свій канал або задати час для відкладеного постингу.</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Технічний стек (Tech Stack)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Оркестрація:</strong> n8n (Масштабний пайплайн із десятками паралельних гілок, Switch-роутерами та Webhooks)</li><br><li><strong class="text-white">Інтерфейс:</strong> Telegram Bot API (Custom Keyboards, Inline Buttons)</li><br><li><strong class="text-white">AI-Моделі:</strong> Google Gemini (аналіз даних з сайту та генерація текстів)</li><br><li><strong class="text-white">Dynamic Design API:</strong> Nano Banano Pro (автоматична генерація складних банерів)</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Бізнес-результат (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Блискавична швидкість:</strong> Час створення професійного промо-посту скоротився з 20-30 хвилин ручної роботи до <strong class="text-white">1.5 хвилини</strong> фонового очікування.</li><br><li><strong class="text-white">Заміна відділу маркетингу:</strong> Система повністю замінила роботу SMM-менеджера та графічного дизайнера. Власник бізнесу може запускати розпродажі прямо зі свого смартфона, стоячи в заторі.</li><br><li><strong class="text-white">Advanced Architecture:</strong> Скріншот дерева цього сценарію в n8n наочно доводить здатність будувати архітектуру Enterprise-рівня, яка не "падає" під час виконання складних розгалужених процесів.</li><br></ul><br><br>---</div>
`
        }
    },
    {
        id: "proj_3",
        image: "assets/event_crm.png",
        title: {
            en: `Event CRM & Attendee Communication Pipeline`,
            ua: `Event CRM & Attendee Communication Pipeline`
        },
        tags: ['n8n', 'Telegram', 'Google Sheets'],
        summary: {
            en: `Event organizers (especially volunteer and educational initiatives) often suffer from a lack of CRM systems. As a user, I filled out the training registration form and faced a "bla...`,
            ua: `Організатори заходів (особливо волонтерські та освітні ініціативи) часто страждають від відсутності CRM-систем. Як користувач, я заповнив форму реєстрації на тренінг і зіткнувся з...`
        },
        content: {
            en: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. The business problem (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Event organizers (especially volunteer and educational initiatives) often suffer from a lack of CRM systems. As a user, I filled out the training registration form and faced a "black hole" <ul class="list-disc pl-5 my-2 space-y-1"><li>no confirmation email or message. The organizers did not have tools for mass communication, which usually leads to a low attendance rate for events: people simply forget or do not know where to go.</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. The Solution and Architecture (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">To solve this problem, I proactively developed a comprehensive automated communication funnel (Event CRM) based on<strong class="text-white">n8n</strong>, which guides the participant from the moment of registration to the collection of feedback after the event.<br><br>-<strong class="text-white">Instant lead capture (Apps Script -> Webhook):</strong>As soon as the participant fills out the Google Form, the<strong class="text-white">Google Apps Script</strong>written by me captures a new row in the table and instantly sends the payload to the Webhook in n8n.<br>-<strong class="text-white">Omnichannel Onboarding (Email -> Telegram):</strong>n8n immediately sends the participant an Email about successful registration. But the main goal of the letter is to transfer a person to the Telegram bot (through the CTA button). This allows organizers to get a direct, free and fast communication channel (unlike mail, where letters get lost in spam).<br>-<strong class="text-white">Dynamic control of attendance (Attendance Logic):</strong>On the eve of the training, the system (according to the schedule) sends a request to the participants in Telegram: "Will you confirm your attendance tomorrow?".<br>  <ul class="list-disc pl-5 my-2 space-y-1"><li>If a person clicks<strong class="text-white">"Yes"</strong>: The bot instantly sends them the exact location, coordinates and directions.</li><br></ul>  <ul class="list-disc pl-5 my-2 space-y-1"><li>If a person presses<strong class="text-white">"No"</strong>: The bot politely replies that it will wait for them next time (and makes room for others).</li><br></ul>-<strong class="text-white">Post-Event communication:</strong>After the event, a separate script automatically sends out a request for feedback.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Tech Stack</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Orchestration:</strong>n8n (Split into microservices: registration, mailing, confirmation, feedback)<br>-<strong class="text-white">Scripting:</strong>Google Apps Script (triggers for changes in Google Sheets)<br>-<strong class="text-white">Communication channels:</strong>Telegram Bot API (custom keyboards, Inline buttons), SMTP/Email Nodes<br>-<strong class="text-white">Data storage:</strong>Google Sheets API (as an improvised CRM)</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Business result (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Maximization of profitability (High Attendance):</strong>Thanks to instant confirmations and reminders, the percentage of people who actually reached the event increased significantly.<br>-<strong class="text-white">Total time savings:</strong>Organizers no longer need to manually call participants or send hundreds of SMS. The process works on 100% autopilot.<br>-<strong class="text-white">Creating a loyal base:</strong>Transferring participants to the Telegram bot allowed the organizers to form their own subscriber base with an extremely high Open Rate (opening of messages) for announcements of future trainings.<br><br><br>---</div>
`,
            ua: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. Проблема бізнесу (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Організатори заходів (особливо волонтерські та освітні ініціативи) часто страждають від відсутності CRM-систем. Як користувач, я заповнив форму реєстрації на тренінг і зіткнувся з "чорною дірою" — жодного листа чи повідомлення з підтвердженням. Організатори не мали інструментів для масової комунікації, що зазвичай призводить до низької доходимості (Attendance Rate) на івенти: люди просто забувають або не знають, куди їхати.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. Рішення та Архітектура (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Щоб вирішити цю проблему, я проактивно розробив комплексну автоматизовану воронку комунікації (Event CRM) на базі <strong class="text-white">n8n</strong>, яка проводить учасника від моменту реєстрації до збору відгуків після події.<br><br><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Миттєве захоплення ліда (Apps Script -> Webhook):</strong> Щойно учасник заповнює Google Форму, написаний мною <strong class="text-white">Google Apps Script</strong> фіксує новий рядок у таблиці і миттєво відправляє payload на Webhook в n8n.</li><br><li><strong class="text-white">Омніканальний Onboarding (Email -> Telegram):</strong> n8n одразу відправляє учаснику Email про успішну реєстрацію. Але головна мета листа — перевести людину в Telegram-бот (через CTA-кнопку). Це дозволяє організаторам отримати прямий, безкоштовний і швидкий канал зв'язку (на відміну від пошти, де листи губляться в спамі).</li><br><li><strong class="text-white">Динамічний контроль присутності (Attendance Logic):</strong> Напередодні тренінгу система (за розкладом) розсилає учасникам у Telegram запит: "Чи підтверджуєте ви свою присутність завтра?".</li><br></ul>  <ul class="list-disc pl-5 my-2 space-y-1"><li>Якщо людина тисне <strong class="text-white">"Так"</strong>: Бот миттєво надсилає їй точну локацію, координати та інструкції щодо проїзду.</li><br></ul>  <ul class="list-disc pl-5 my-2 space-y-1"><li>Якщо людина тисне <strong class="text-white">"Ні"</strong>: Бот ввічливо відповідає, що чекатиме її наступного разу (і звільняє місце для інших).</li><br><li><strong class="text-white">Post-Event комунікація:</strong> Після заходу окремий сценарій автоматично розсилає запит на збір відгуків.</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Технічний стек (Tech Stack)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Оркестрація:</strong> n8n (Розділено на мікросервіси: реєстрація, розсилка, підтвердження, відгуки)</li><br><li><strong class="text-white">Скриптинг:</strong> Google Apps Script (тригери на зміни в Google Sheets)</li><br><li><strong class="text-white">Канали комунікації:</strong> Telegram Bot API (кастомні клавіатури, Inline-кнопки), SMTP/Email Nodes</li><br><li><strong class="text-white">Зберігання даних:</strong> Google Sheets API (як імпровізована CRM)</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Бізнес-результат (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Максимізація доходимості (High Attendance):</strong> Завдяки миттєвим підтвердженням та нагадуванням, відсоток людей, які реально дійшли до івенту, суттєво зріс.</li><br><li><strong class="text-white">Тотальна економія часу:</strong> Організаторам більше не потрібно вручну дзвонити учасникам чи розсилати сотні SMS. Процес працює на 100% автопілоті.</li><br><li><strong class="text-white">Створення лояльної бази:</strong> Переведення учасників у Telegram-бот дозволило організаторам сформувати власну базу підписників з надзвичайно високим Open Rate (відкриттям повідомлень) для анонсів майбутніх тренінгів.</li><br></ul><br><br>---</div>
`
        }
    },
    {
        id: "proj_4",
        image: "assets/influencer.png",
        title: {
            en: `Influencer Data Pipeline: Make.com to n8n Migration`,
            ua: `Influencer Data Pipeline: Make.com to n8n Migration`
        },
        tags: ['n8n', 'Make.com', 'Google Sheets', 'OpenAI'],
        summary: {
            en: `To launch targeted marketing campaigns, the client needed to analyze arrays of Instagram profiles of bloggers (influencers) every day. Manual screening by the managers department w...`,
            ua: `Для запуску таргетованих маркетингових кампаній клієнту потрібно було щодня аналізувати масиви Instagram-профілів блогерів (Influencers). Ручний скрінінг відділом менеджерів був не...`
        },
        content: {
            en: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. The business problem (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">To launch targeted marketing campaigns, the client needed to analyze arrays of Instagram profiles of bloggers (influencers) every day. Manual screening by the managers department was ineffective. <br>I developed the first version of comprehensive automation at<strong class="text-white">Make.com</strong>that collected metrics, calculated engagement rates and determined the country of origin of the audience through AI.<br>However, when the database grew to<strong class="text-white">100,000+ profiles</strong>, a critical problem emerged: Make.com's billing architecture (pay per operation/node) made analyzing huge data sets uneconomical. The budget for infrastructure began to "eat" the profit.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. The Solution and Architecture (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">In order to save the client's budget and ensure unlimited scaling, I performed a complete migration of the logic to<strong class="text-white">Self-Hosted n8n</strong>.<br>-<strong class="text-white">Calculation optimization (JavaScript):</strong>Make.com used dozens of separate tools for complex math calculations (such as determining account "heat" metrics, ER_AVG, ER_MED), which burned through limits. In n8n, I rewrote all this logic in pure<strong class="text-white">JavaScript (Code Node)</strong>. Processing of data arrays began to take place within one node without additional costs.<br>-<strong class="text-white">Deep Data Enrichment (Apify + AI):</strong>The system automatically starts scraping through<strong class="text-white">Apify</strong>to collect the latest posts and comments. Since the standard APIs do not provide information about the geolocation of the audience, the comment array is sent to<strong class="text-white">ChatGPT (OpenAI)</strong>. AI performs semantic analysis of language and context, determining with high accuracy the probable country of origin of the blogger.<br>-<strong class="text-white">Base automation:</strong>Enriched, filtered and mathematically calculated data are automatically exported to Google Sheets, where managers only have to decide on cooperation based on ready-made coefficients.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Tech Stack</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Platforms:</strong>Migration of logic from Make.com to n8n<br>-<strong class="text-white">Programming languages:</strong>JavaScript (for optimizing mathematical calculations and arrays in Code Nodes)<br>-<strong class="text-white">Scraping & Data:</strong>Apify (Instagram Scrapers)<br>-<strong class="text-white">AI models:</strong>OpenAI API (semantic analysis of text to determine geography)<br>-<strong class="text-white">Integrations:</strong>Google Sheets API</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Business result (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Critical cost reduction (Massive Cost Reduction):</strong>Switching to n8n using custom JS code allowed us to process<strong class="text-white">unlimited amount of data</strong>for a fixed cost of renting a server (up to $10/month).<br>-<strong class="text-white">Elimination of manual analysis:</strong>The system completely replaced the manual screening of profiles by managers. The business receives a "cleaned" list of ideal candidates with pre-calculated rates of return (ER).<br>-<strong class="text-white">Big Data Scale:</strong>Created a highly optimized pipeline that easily digests databases of 100,000+ profiles, which was technically or financially impossible to implement in standard Make.com.<br><br><br>---</div>
`,
            ua: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. Проблема бізнесу (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Для запуску таргетованих маркетингових кампаній клієнту потрібно було щодня аналізувати масиви Instagram-профілів блогерів (Influencers). Ручний скрінінг відділом менеджерів був неефективним. <br>Я розробив першу версію комплексної автоматизації на <strong class="text-white">Make.com</strong>, яка збирала метрики, розраховувала коефіцієнти залученості та через ШІ визначала країну походження аудиторії.<br>Проте, коли база виросла до <strong class="text-white">100 000+ профілів</strong>, з'явилася критична проблема: архітектура білінгу Make.com (оплата за кожну операцію/ноду) зробила аналіз величезних масивів даних економічно невигідним. Бюджет на інфраструктуру став "з'їдати" прибуток.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. Рішення та Архітектура (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Щоб врятувати бюджет клієнта і забезпечити безлімітне масштабування, я здійснив повну міграцію логіки на <strong class="text-white">Self-Hosted n8n</strong>.<br><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Оптимізація обчислень (JavaScript):</strong> У Make.com для складних математичних прорахунків (наприклад, визначення метрик "прогрітості" акаунта, ER_AVG, ER_MED) використовувалися десятки окремих інструментів, що спалювало ліміти. В n8n я переписав усю цю логіку на чистому <strong class="text-white">JavaScript (Code Node)</strong>. Обробка масивів даних стала відбуватися всередині однієї ноди без додаткових витрат.</li><br><li><strong class="text-white">Deep Data Enrichment (Apify + AI):</strong> Система автоматично запускає скрейпінг через <strong class="text-white">Apify</strong> для збору останніх публікацій та коментарів. Оскільки стандартні API не дають інформацію про геолокацію аудиторії, масив коментарів відправляється у <strong class="text-white">ChatGPT (OpenAI)</strong>. ШІ проводить семантичний аналіз мови та контексту, з високою точністю визначаючи ймовірну країну походження блогера.</li><br><li><strong class="text-white">Автоматизація бази:</strong> Збагачені, відфільтровані та математично прораховані дані автоматично експортуються у Google Sheets, де менеджерам залишається лише прийняти рішення про співпрацю на основі готових коефіцієнтів.</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Технічний стек (Tech Stack)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Платформи:</strong> Міграція логіки з Make.com на n8n</li><br><li><strong class="text-white">Мови програмування:</strong> JavaScript (для оптимізації математичних розрахунків та масивів у Code Nodes)</li><br><li><strong class="text-white">Scraping & Data:</strong> Apify (Instagram Scrapers)</li><br><li><strong class="text-white">ШІ-моделі:</strong> OpenAI API (семантичний аналіз тексту для визначення географії)</li><br><li><strong class="text-white">Інтеграції:</strong> Google Sheets API</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Бізнес-результат (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Критичне зниження витрат (Massive Cost Reduction):</strong> Перехід на n8n з використанням кастомного JS-коду дозволив обробляти <strong class="text-white">необмежену кількість даних</strong> за фіксовану вартість оренди сервера (до $10/міс).</li><br><li><strong class="text-white">Ліквідація ручного аналізу:</strong> Система повністю замінила ручний скрінінг профілів менеджерами. Бізнес отримує "очищений" список ідеальних кандидатів із заздалегідь прорахованими коефіцієнтами рентабельності (ER).</li><br><li><strong class="text-white">Big Data Scale:</strong> Створено високооптимізований конвеєр, який легко перетравлює бази у 100 000+ профілів, що було технічно або фінансово неможливо реалізувати у стандартному Make.com.</li><br></ul><br><br>---</div>
`
        }
    },
    {
        id: "proj_5",
        image: "assets/reels.png",
        title: {
            en: `Social Media Automation: Reels Analyzer & Auto-Poster`,
            ua: `Social Media Automation: Reels Analyzer & Auto-Poster`
        },
        tags: ['n8n', 'Gemini', 'Telegram', 'Facebook', 'Google Sheets'],
        summary: {
            en: `Content creators and SMM agencies analyze dozens of competitors' videos (Instagram Reels) every day to create references. The manual process goes like this: copy the link -> go to...`,
            ua: `Контент-мейкери та SMM-агентства щодня аналізують десятки відео конкурентів (Instagram Reels) для створення референсів. Ручний процес виглядає так: скопіювати посилання -> піти на...`
        },
        content: {
            en: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. The business problem (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Content creators and SMM agencies analyze dozens of competitors' videos (Instagram Reels) every day to create references. The manual process goes like this: copy the link -> go to a 3rd party site (with tons of ads) to download the video -> watch it -> manually write a summary/description -> copy it all into a Google Sheets pivot table. The client wanted to reduce this multi-step process to a single action.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. The Solution and Architecture (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">I developed a Telegram bot based on<strong class="text-white">n8n</strong>, which works as a smart content assistant. Pipeline does all the dirty work in seconds:<br>-<strong class="text-white">Data extraction (Scraping):</strong>The user throws a link to the Instagram Reel into the Telegram bot. The system intercepts it (Telegram Trigger) and through<strong class="text-white">Apify / RapidAPI</strong>"extracts" a clean video file in maximum quality.<br>-<strong class="text-white">Multimodal AI analytics:</strong>Video is not just downloaded, but sent in parallel to<strong class="text-white">Multimodal LLM (Gemini)</strong>. AI "views" the video and generates a detailed text description of what is happening there (for example: *"The video demonstrates the technique of modifying the growth of the fetus..."*).<br>-<strong class="text-white">Storage and Reporting:</strong>Clean video is automatically uploaded to Google Drive. The system then takes the file link, adds an AI-generated description, and writes it as a new row in Google Sheets. The final report is instantly delivered to the client in Telegram.<br>-<strong class="text-white">Autoposting (Meta Developer API):</strong>As a logical continuation of the architecture, the system is able to automatically post processed content back to Instagram. For this, legal interaction through the official<strong class="text-white">Meta Graph API</strong>with the generation of long-lived access tokens (Long-Lived Access Tokens for 60 days) is configured, which eliminates the risk of account ban.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Tech Stack</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Orchestration:</strong>n8n (work with Binary Data, Merge Nodes, Telegram Webhooks)<br>-<strong class="text-white">Scraping & APIs:</strong>Apify, RapidAPI<br>-<strong class="text-white">AI Models:</strong>Gemini Vision (for dynamic video content analysis)<br>-<strong class="text-white">Social Media API:</strong>Meta Developer Graph API (Instagram Auto-publishing)<br>-<strong class="text-white">Integrations:</strong>Google Drive API, Google Sheets API, Telegram Bot API</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Business result (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Time savings (10 minutes -> 1 second):</strong>An operation that used to take 10 minutes of manual labor now only needs to send one message to messenger.<br>-<strong class="text-white">Automatic reference database:</strong>A structured, easy-to-search table with ready-made descriptions and clean video files for the content plan is automatically created for the client.<br>-<strong class="text-white">Stability (Anti-Ban):</strong>Thanks to the correct handling of Facebook/Instagram tokens via official APIs, autoposting works stably and safely for business accounts.<br><br><br>---</div>
`,
            ua: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. Проблема бізнесу (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Контент-мейкери та SMM-агентства щодня аналізують десятки відео конкурентів (Instagram Reels) для створення референсів. Ручний процес виглядає так: скопіювати посилання -> піти на сторонній сайт (з купою реклами), щоб завантажити відео -> подивитися його -> вручну написати резюме/опис -> скопіювати все це у зведену таблицю Google Sheets. Клієнт хотів звести цей багатокроковий процес до однієї дії.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. Рішення та Архітектура (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Я розробив Telegram-бота на базі <strong class="text-white">n8n</strong>, який працює як розумний контент-асистент. Пайплайн виконує всю брудну роботу за кілька секунд:<br><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Екстракція даних (Scraping):</strong> Користувач кидає посилання на Instagram Reel у Telegram-бот. Система перехоплює його (Telegram Trigger) та через <strong class="text-white">Apify / RapidAPI</strong> "витягує" чистий відеофайл у максимальній якості.</li><br><li><strong class="text-white">Мультимодальна AI-аналітика:</strong> Відео не просто завантажується, а паралельно відправляється у <strong class="text-white">Multimodal LLM (Gemini)</strong>. ШІ "переглядає" ролик і генерує детальний текстовий опис того, що там відбувається (наприклад: *"Відео демонструє техніку модифікації росту плоду..."*).</li><br><li><strong class="text-white">Сховище та Звітність:</strong> Чисте відео автоматично завантажується на Google Drive. Після цього система бере посилання на файл, додає згенерований ШІ опис і записує це як новий рядок у Google Sheets. Фінальний звіт миттєво приходить клієнту в Telegram.</li><br><li><strong class="text-white">Автопостинг (Meta Developer API):</strong> Як логічне продовження архітектури, система вміє автоматично публікувати оброблений контент назад в Instagram. Для цього налаштовано легальну взаємодію через офіційний <strong class="text-white">Meta Graph API</strong> з генерацією довгострокових токенів доступу (Long-Lived Access Tokens на 60 діб), що виключає ризик бану акаунта.</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Технічний стек (Tech Stack)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Оркестрація:</strong> n8n (робота з Binary Data, Merge Nodes, Telegram Webhooks)</li><br><li><strong class="text-white">Scraping & APIs:</strong> Apify, RapidAPI</li><br><li><strong class="text-white">AI Models:</strong> Gemini Vision (для аналізу динамічного відеоконтенту)</li><br><li><strong class="text-white">Social Media API:</strong> Meta Developer Graph API (Instagram Auto-publishing)</li><br><li><strong class="text-white">Інтеграції:</strong> Google Drive API, Google Sheets API, Telegram Bot API</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Бізнес-результат (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Економія часу (10 хвилин -> 1 секунда):</strong> Операція, яка займала 10 хвилин ручної праці, тепер потребує лише відправки одного повідомлення в месенджер.</li><br><li><strong class="text-white">Автоматична база референсів:</strong> У клієнта автоматично формується структурована, зручна для пошуку таблиця з готовими описами та чистими відеофайлами для контент-плану.</li><br><li><strong class="text-white">Стабільність (Anti-Ban):</strong> Завдяки правильній роботі з токенами Facebook/Instagram через офіційні API, автопостинг працює стабільно і безпечно для бізнес-акаунтів.</li><br></ul><br><br>---</div>
`
        }
    },
    {
        id: "proj_6",
        image: "assets/pdf_rag.png",
        title: {
            en: `Multimodal AI-Agent (Complex PDF RAG)`,
            ua: `Multimodal AI-Agent (Complex PDF RAG)`
        },
        tags: ['n8n', 'Gemini', 'PDF RAG', 'OpenAI'],
        summary: {
            en: `Modern companies have huge knowledge bases (technical instructions, reports, manuals), which are stored in the format of complex PDF documents. Conventional chatbots or classical R...`,
            ua: `Сучасні компанії мають величезні бази знань (технічні інструкції, звіти, мануали), які зберігаються у форматі складних PDF-документів. Звичайні чат-боти або класичні RAG-системи (R...`
        },
        content: {
            en: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. The business problem (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Modern companies have huge knowledge bases (technical instructions, reports, manuals), which are stored in the format of complex PDF documents. Conventional chatbots or classical RAG systems (Retrieval-Augmented Generation) have a critical drawback <ul class="list-disc pl-5 my-2 space-y-1"><li>they are "blind". They are able to extract only plain text from PDF, ignoring drawings, graphs, tables and diagrams, without which technical instructions often lose all meaning.</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. The Solution and Architecture (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">To solve this problem, I built a<strong class="text-white">Multimodal RAG Pipeline</strong>in n8n based on a large car manual in English. <br><br>The system works in two stages:<br>1.<strong class="text-white">Ingestion Pipeline (Smart Download):</strong>A complex PDF file is sent via API to<strong class="text-white">Mistral OCR</strong>. This model is able to recognize not only text, but also the spatial arrangement of elements (images, graphs). The text is split into semantic blocks (Recursive Character Text Splitter), converted into vectors through<strong class="text-white">OpenAI Embeddings</strong>and loaded into the vector database<strong class="text-white">Supabase Vector Store</strong>. In parallel, the system processes and saves the cut images (through Base64 conversion).<br>2.<strong class="text-white">Autonomous AI Chat (Client part):</strong>The user asks a question in the chat in his native language (for example: *"how to reset the oil change indicator?"*). AI-Agent (based on<strong class="text-white">Google Gemini</strong>) automatically goes to the vector database, finds the required fragment in the English manual, translates it and — most importantly —<strong class="text-white">outputs not only the text of the instructions, but also the original images/diagrams</strong>of the steering wheel and instrument panel from the PDF file in the chat.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Tech Stack</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Orchestration and AI-Agents:</strong>n8n (Advanced AI nodes, Tool Calling)<br>-<strong class="text-white">Computer Vision / OCR:</strong>Mistral OCR API (processing complex PDFs)<br>-<strong class="text-white">Vector DB:</strong>Supabase (pgvector)<br>-<strong class="text-white">AI Models:</strong>OpenAI API (for building Embeddings), Google Gemini Chat Model (for agent logic and response generation)<br>-<strong class="text-white">Data processing:</strong>Base64 Image Processing, Recursive Text Splitter</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Business result (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Multimodality (Multimodal RAG):</strong>The main limitation of standard systems was broken — the bot learned to respond not only with text, but also with relevant pictures and graphs from the documentation.<br>-<strong class="text-white">Overcoming the language barrier:</strong>Employees or customers can work with thousands of pages of complex English-language technical documentation, asking questions in Ukrainian and instantly receiving a translated answer.<br>-<strong class="text-white">Enterprise-ready:</strong>Such an architecture is an ideal solution for the automation of support services (Customer Support), the work of service engineers, compliance departments or medical professionals who daily search for information in complex corporate databases.<br><br><br>---</div>
`,
            ua: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. Проблема бізнесу (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Сучасні компанії мають величезні бази знань (технічні інструкції, звіти, мануали), які зберігаються у форматі складних PDF-документів. Звичайні чат-боти або класичні RAG-системи (Retrieval-Augmented Generation) мають критичний недолік — вони "сліпі". Вони здатні витягувати з PDF лише голий текст, ігноруючи креслення, графіки, таблиці та схеми, без яких технічні інструкції часто втрачають будь-який сенс.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. Рішення та Архітектура (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Для вирішення цієї проблеми я побудував <strong class="text-white">Мультимодальний RAG-пайплайн</strong> в n8n на прикладі великого автомобільного мануала англійською мовою. <br><br>Система працює у два етапи:<br>1. <strong class="text-white">Ingestion Pipeline (Розумне завантаження):</strong> Складний PDF-файл відправляється через API до <strong class="text-white">Mistral OCR</strong>. Ця модель здатна розпізнавати не лише текст, а й просторове розташування елементів (зображень, графіків). Текст розбивається на семантичні блоки (Recursive Character Text Splitter), перетворюється на вектори через <strong class="text-white">OpenAI Embeddings</strong> і завантажується у векторну базу <strong class="text-white">Supabase Vector Store</strong>. Паралельно система обробляє та зберігає вирізані зображення (через Base64-конвертацію).<br>2. <strong class="text-white">Autonomous AI Chat (Клієнтська частина):</strong> Користувач задає питання в чаті рідною мовою (наприклад: *"як скинути індикатор заміни мастила?"*). AI-Агент (на базі <strong class="text-white">Google Gemini</strong>) автоматично йде у векторну базу, знаходить потрібний фрагмент в англомовному мануалі, перекладає його і — найголовніше — <strong class="text-white">виводить у чат не лише текст інструкції, а й оригінальні зображення/схеми</strong> керма та панелі приладів з PDF-файлу.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Технічний стек (Tech Stack)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Оркестрація та AI-Агенти:</strong> n8n (Advanced AI nodes, Tool Calling)</li><br><li><strong class="text-white">Computer Vision / OCR:</strong> Mistral OCR API (обробка складних PDF)</li><br><li><strong class="text-white">Векторна База (Vector DB):</strong> Supabase (pgvector)</li><br><li><strong class="text-white">AI Models:</strong> OpenAI API (для побудови Embeddings), Google Gemini Chat Model (для логіки агента та генерації відповідей)</li><br><li><strong class="text-white">Обробка даних:</strong> Base64 Image Processing, Recursive Text Splitter</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Бізнес-результат (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Мультимодальність (Multimodal RAG):</strong> Зламано головне обмеження стандартних систем — бот навчився відповідати не лише текстом, а й релевантними картинками та графіками з документації.</li><br><li><strong class="text-white">Подолання мовного бар'єра:</strong> Співробітники або клієнти можуть працювати з тисячами сторінок складної англомовної техдокументації, ставлячи запитання українською мовою та миттєво отримуючи перекладену відповідь.</li><br><li><strong class="text-white">Enterprise-ready:</strong> Така архітектура є ідеальним рішенням для автоматизації служб підтримки (Customer Support), роботи сервісних інженерів, відділів комплаєнсу або медичних працівників, які щодня шукають інформацію у складних корпоративних базах даних.</li><br></ul><br><br>---</div>
`
        }
    },
    {
        id: "proj_7",
        image: "assets/n8n_arch.png",
        title: {
            en: `Secure Self-Hosted n8n Architecture`,
            ua: `Secure Self-Hosted n8n Architecture`
        },
        tags: ['n8n', 'Make.com', 'Docker'],
        summary: {
            en: `When scaling a business, the use of cloud automation services (Cloud n8n, Make.com, Zapier) becomes a "bottleneck". Two main problems appear: firstly, huge monthly bills due to str...`,
            ua: `При масштабуванні бізнесу використання хмарних сервісів автоматизації (Cloud n8n, Make.com, Zapier) стає "вузьким місцем". З'являються дві головні проблеми: по-перше, величезні щом...`
        },
        content: {
            en: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. The business problem (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">When scaling a business, the use of cloud automation services (Cloud n8n, Make.com, Zapier) becomes a "bottleneck". Two main problems appear: firstly, huge monthly bills due to strict limits on the number of executions; secondly, companies with strict privacy policies cannot afford to process sensitive customer data (CRM, payments) on third-party public servers.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. The Solution and Architecture (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">For complex or large-scale projects, I develop and deploy turnkey autonomous infrastructure directly on the customer's servers. <br>-<strong class="text-white">Docker Orchestration:</strong>The system kernel (n8n) and required databases (PostgreSQL) are deployed in a fully isolated and controlled environment using Docker Compose. This makes the system as stable and portable as possible.<br>-<strong class="text-white">Security and Cloudflare:</strong>Even in cases where the client has very tight network settings, I integrate<strong class="text-white">Cloudflare Tunnels</strong>. This allows you to hide the server's real IP address from attackers, securely encrypt traffic and configure access exclusively through "white lists" (IP whitelisting).</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Tech Stack</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Infrastructure:</strong>Linux VPS, Docker, Docker Compose<br>-<strong class="text-white">Security and Networking:</strong>Cloudflare Tunnels, Zero Trust, IP Whitelisting<br>-<strong class="text-white">Systems:</strong>n8n (Self-hosted Enterprise-grade setup), PostgreSQL</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Business result (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Total Savings (Cost Reduction):</strong>The cost of maintaining the system drops to $5-$10/month (the cost of renting a basic VPS), instead of hundreds of dollars for cloud subscriptions.<br>-<strong class="text-white">Unlimited scaling:</strong>Any restrictions on the number of workflow runs are removed <ul class="list-disc pl-5 my-2 space-y-1"><li>a business can handle millions of transactions without any additional fees.</li><br></ul>-<strong class="text-white">One hundred percent data privacy (Data Privacy):</strong>All leads, correspondence and commercial secrets never leave the boundaries of the client's own server.<br><br><br>---</div>
`,
            ua: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. Проблема бізнесу (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">При масштабуванні бізнесу використання хмарних сервісів автоматизації (Cloud n8n, Make.com, Zapier) стає "вузьким місцем". З'являються дві головні проблеми: по-перше, величезні щомісячні рахунки через жорсткі ліміти на кількість запусків (executions); по-друге, компанії зі строгими політиками конфіденційності не можуть дозволити собі обробляти чутливі дані клієнтів (CRM, платежі) на сторонніх публічних серверах.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. Рішення та Архітектура (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Для складних або масштабних проєктів я розробляю та розгортаю автономну інфраструктуру "під ключ" безпосередньо на серверах замовника. <br><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Docker-оркестрація:</strong> Ядро системи (n8n) та необхідні бази даних (PostgreSQL) розгортаються у повністю ізольованому та контрольованому середовищі за допомогою Docker Compose. Це дозволяє зробити систему максимально стабільною та портативною.</li><br><li><strong class="text-white">Безпека та Cloudflare:</strong> Навіть у випадках, коли клієнт має дуже жорсткі мережеві налаштування, я інтегрую <strong class="text-white">Cloudflare Tunnels</strong>. Це дозволяє приховати реальну IP-адресу сервера від зловмисників, надійно зашифрувати трафік та налаштувати доступ виключно через "білі списки" (IP whitelisting).</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Технічний стек (Tech Stack)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Інфраструктура:</strong> Linux VPS, Docker, Docker Compose</li><br><li><strong class="text-white">Безпека та Мережа:</strong> Cloudflare Tunnels, Zero Trust, IP Whitelisting</li><br><li><strong class="text-white">Системи:</strong> n8n (Self-hosted Enterprise-grade setup), PostgreSQL</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Бізнес-результат (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Тотальна економія (Cost Reduction):</strong> Вартість утримання системи падає до $5-$10/місяць (вартість оренди базового VPS), замість сотень доларів за хмарні підписки.</li><br><li><strong class="text-white">Безлімітне масштабування:</strong> Знято будь-які обмеження на кількість запусків воркфлоу — бізнес може обробляти мільйони операцій без жодних доплат.</li><br><li><strong class="text-white">Стовідсоткова приватність даних (Data Privacy):</strong> Усі ліди, листування та комерційна таємниця ніколи не залишають межі власного сервера клієнта.</li><br></ul><br><br>---</div>
`
        }
    },
    {
        id: "proj_8",
        image: "assets/telegram.png",
        title: {
            en: `Telegram "Radar" Lead Generation System`,
            ua: `Telegram "Radar" Lead Generation System`
        },
        tags: ['n8n', 'Python', 'Telegram', 'Userbot', 'OpenAI'],
        summary: {
            en: `For many businesses (especially in B2B and services), Telegram groups are a "golden vein" of customers. However, manually monitoring dozens of chats takes hours of time every day....`,
            ua: `Для багатьох бізнесів (особливо у B2B та послугах) Telegram-групи є "золотою жилою" клієнтів. Проте ручний моніторинг десятків чатів займає години часу щодня. Клієнтам була потрібн...`
        },
        content: {
            en: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. The business problem (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">For many businesses (especially in B2B and services), Telegram groups are a "golden vein" of customers. However, manually monitoring dozens of chats takes hours of time every day. Clients needed a system that would "listen" to target groups 24/7 from under a real account, identify requests by keywords (for example, "looking for a contractor", "need help") and instantly notify about it, filtering out spam.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. The Solution and Architecture (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">I have developed a<strong class="text-white">Telegram Radar</strong>system that works as a smart "lead vacuum cleaner". <br>The system consists of two key components:<br>1.<strong class="text-white">Listener (Python Userbot):</strong>Written in Python using the<strong class="text-white">Telethon</strong>library, the script runs on its own Linux VPS server 24/7. It is connected to a real Telegram account (to bypass the limitations of regular bots) and monitors more than 30 thematic channels and groups in real time.<br>2.<strong class="text-white">Orchestrator (n8n):</strong>As soon as a message with a given keyword appears, a Python script sends it via Webhook to the<strong class="text-white">n8n</strong>system. Logic is configured inside n8n: the message can be checked by AI for intelligent filtering (to weed out spam or irrelevant context), after which it is instantly sent to the client in the form of a convenient notification in a personal Telegram bot.<br><br>*(Note: on the basis of the same architecture, it is possible to connect an AI agent to automatically start a dialogue with ice).*</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Tech Stack</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Backend:</strong>Python (\`Telethon' library)<br>-<strong class="text-white">Orchestration and Automation:</strong>n8n (Webhooks, Data Processing)<br>-<strong class="text-white">Infrastructure:</strong>Own VPS Server<br>-<strong class="text-white">Integrations:</strong>Telegram API (Userbot + Bot API), OpenAI API (optional for filtering)</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Business result (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Scale:</strong>Simultaneous uninterrupted monitoring of<strong class="text-white">more than 30 active groups</strong>.<br>-<strong class="text-white">Speed:</strong>The time from publishing a message by a potential client to receiving a notification by the customer is less than 1-2 seconds.<br>-<strong class="text-white">Efficiency (ROI):</strong>Complete elimination of manual work. The customer receives already filtered, "warm" requests (Real-time leads) directly to his bot, which allows him to respond to requests first and take customers faster than competitors.<br><br><br>---</div>
`,
            ua: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. Проблема бізнесу (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Для багатьох бізнесів (особливо у B2B та послугах) Telegram-групи є "золотою жилою" клієнтів. Проте ручний моніторинг десятків чатів займає години часу щодня. Клієнтам була потрібна система, яка б "слухала" цільові групи 24/7 з-під реального акаунта, виявляла запити за ключовими словами (наприклад, "шукаю підрядника", "потрібна допомога") та миттєво сповіщала про це, відсіюючи спам.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. Рішення та Архітектура (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Я розробив систему <strong class="text-white">Telegram Radar</strong>, яка працює як розумний "пилосос лідів". <br>Система складається з двох ключових компонентів:<br>1. <strong class="text-white">Слухач (Python Userbot):</strong> Написаний на Python з використанням бібліотеки <strong class="text-white">Telethon</strong>, скрипт працює на власному Linux VPS-сервері 24/7. Він підключений до реального Telegram-акаунта (щоб оминати обмеження звичайних ботів) і моніторить понад 30 тематичних каналів та груп у реальному часі.<br>2. <strong class="text-white">Оркестратор (n8n):</strong> Щойно з'являється повідомлення із заданим ключовим словом, Python-скрипт відправляє його через Webhook у систему <strong class="text-white">n8n</strong>. Усередині n8n налаштована логіка: повідомлення може проходити перевірку через ШІ для розумної фільтрації (щоб відсіяти спам чи нерелевантний контекст), після чого миттєво відправляється клієнту у вигляді зручного сповіщення в особистий Telegram-бот.<br><br>*(Примітка: на базі цієї ж архітектури можливе підключення ШІ-агента для автоматичного старту діалогу з лідом).*</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Технічний стек (Tech Stack)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Backend:</strong> Python (бібліотека \`Telethon\`)</li><br><li><strong class="text-white">Оркестрація та Автоматизація:</strong> n8n (Webhooks, Data Processing)</li><br><li><strong class="text-white">Інфраструктура:</strong> Власний VPS Server</li><br><li><strong class="text-white">Інтеграції:</strong> Telegram API (Userbot + Bot API), OpenAI API (опціонально для фільтрації)</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Бізнес-результат (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Масштаб:</strong> Одночасний безперебійний моніторинг <strong class="text-white">понад 30 активних груп</strong>.</li><br><li><strong class="text-white">Швидкість:</strong> Час від публікації повідомлення потенційним клієнтом до отримання сповіщення замовником складає менше 1-2 секунд.</li><br><li><strong class="text-white">Ефективність (ROI):</strong> Повна ліквідація ручної роботи. Замовник отримує вже відфільтровані, "теплі" запити (Real-time leads) прямо у свій бот, що дозволяє реагувати на запити першим і забирати клієнтів швидше за конкурентів.</li><br></ul><br><br>---</div>
`
        }
    },
    {
        id: "proj_9",
        image: "assets/travel.png",
        title: {
            en: `Autonomous Travel News Autoblogger`,
            ua: `Autonomous Travel News Autoblogger`
        },
        tags: ['n8n', 'Vertex AI', 'Telegram', 'Facebook', 'Firecrawl'],
        summary: {
            en: `It is critical for a travel agency to maintain constant activity on social networks (Facebook) in order to be visible to customers. However, searching for fresh news, tourism trend...`,
            ua: `Для туристичної агенції критично важливо підтримувати постійну активність у соціальних мережах (Facebook), щоб бути на виду у клієнтів. Однак, пошук свіжих новин, трендів туризму т...`
        },
        content: {
            en: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. The business problem (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">It is critical for a travel agency to maintain constant activity on social networks (Facebook) in order to be visible to customers. However, searching for fresh news, tourism trends and writing posts daily requires hiring a separate SMM manager. The client made a request: to create a system that would independently generate a content plan, search for fresh news and automatically manage the agency's Facebook page.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. The Solution and Architecture (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">I developed a fully autonomous "AI Newsroom" based on<strong class="text-white">n8n</strong>, which works as a full-fledged newsroom without any human intervention.<br><br>-<strong class="text-white">Dynamic schedule (JS Routing):</strong>Instead of static prompts, I wrote a JavaScript module that contains a content matrix per week. Depending on the day (via \`new Date().getDay()\`), the script issues specific search requests to the system. For example: on Monday <ul class="list-disc pl-5 my-2 space-y-1"><li>travel hacks and technologies (eSIM); on Wednesday — budget routes and discounts; on Friday - world festivals and food. Also, negative words (for example, \`-war-russia') for brand safety are immediately written in the code.</li><br></ul>-<strong class="text-white">Web Scraping & Research:</strong>After receiving requests for the current day, n8n turns to<strong class="text-white">Firecrawl</strong>, which crawls the web and pulls the latest travel industry news and articles for the current week.<br>-<strong class="text-white">AI-Generation (Vertex AI):</strong>The entire array of "raw" news is sent to<strong class="text-white">Google Vertex AI</strong>. The model analyzes the fact and generates from it a single, well-written post for Facebook, following the style of the travel agency. Additionally, AI generates a thematic image (for example, a girl with a laptop near the sea for a post about Digital Nomad).<br>-<strong class="text-white">Distribution:</strong>The finished text and images are automatically published on the Facebook page.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Tech Stack</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Orchestration:</strong>n8n (Cron Triggers, JS Code Nodes for complex schedule logic)<br>-<strong class="text-white">Search & Data Extraction:</strong>Firecrawl API (search for current news in real time)<br>-<strong class="text-white">AI models:</strong>Google Vertex AI (text generation based on real facts), AI Image Generation<br>-<strong class="text-white">Integrations:</strong>Facebook Pages API, Telegram API (for logging and verification)</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Business result (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Zero-Touch Automation:</strong>The question "what to fast today" is closed forever. The agency page lives a life of its own, constantly being filled with fresh, relevant content.<br>-<strong class="text-white">Budget savings (Cost Savings):</strong>The agency completely saved the budget on the basic services of SMM and copywriter.<br>-<strong class="text-white">Factual accuracy (Grounded AI):</strong>Since the text generation is based on Firecrawl search results, the bot does not create "hallucinations", but publishes real news, trends and prices collected from the Internet.<br><br><br>---</div>
`,
            ua: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. Проблема бізнесу (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Для туристичної агенції критично важливо підтримувати постійну активність у соціальних мережах (Facebook), щоб бути на виду у клієнтів. Однак, пошук свіжих новин, трендів туризму та щоденне написання постів вимагає найму окремого SMM-менеджера. Клієнт звернувся із запитом: створити систему, яка б самостійно генерувала контент-план, шукала свіжі новини та автоматично вела Facebook-сторінку агенції.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. Рішення та Архітектура (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Я розробив повністю автономний "AI Newsroom" на базі <strong class="text-white">n8n</strong>, який працює як повноцінна редакція без жодного втручання людини.<br><br><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Динамічний розклад (JS Routing):</strong> Замість статичних промптів я написав JavaScript-модуль, який містить контент-матрицю на тиждень. Залежно від дня (через \`new Date().getDay()\`), скрипт видає системі конкретні пошукові запити. Наприклад: у понеділок — тревел-хаки та технології (eSIM); у середу — бюджетні маршрути та знижки; у п'ятницю — світові фестивалі та їжа. Також у коді одразу прописані мінус-слова (наприклад, \`-war -russia\`) для безпеки бренду (Brand Safety).</li><br><li><strong class="text-white">Web Scraping & Research:</strong> Отримавши запити на поточний день, n8n звертається до <strong class="text-white">Firecrawl</strong>, який сканує інтернет і витягує найсвіжіші новини та статті з тревел-індустрії за поточний тиждень.</li><br><li><strong class="text-white">AI-Генерація (Vertex AI):</strong> Весь масив "сирих" новин відправляється до <strong class="text-white">Google Vertex AI</strong>. Модель аналізує фактаж і генерує з нього єдиний, якісно написаний пост для Facebook, дотримуючись стилістики турагенції. Додатково ШІ генерує тематичне зображення (наприклад, дівчина з ноутбуком біля моря для поста про Digital Nomad).</li><br><li><strong class="text-white">Дистрибуція:</strong> Готовий текст та зображення автоматично публікуються на сторінці Facebook.</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Технічний стек (Tech Stack)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Оркестрація:</strong> n8n (Cron Triggers, JS Code Nodes для складної логіки розкладу)</li><br><li><strong class="text-white">Search & Data Extraction:</strong> Firecrawl API (пошук актуальних новин у реальному часі)</li><br><li><strong class="text-white">ШІ-моделі:</strong> Google Vertex AI (генерація текстів на основі реального фактажу), AI Image Generation</li><br><li><strong class="text-white">Інтеграції:</strong> Facebook Pages API, Telegram API (для логування та перевірки)</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Бізнес-результат (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Zero-Touch Automation:</strong> Питання "що постити сьогодні" закрите назавжди. Сторінка агенції живе власним життям, постійно наповнюючись свіжим, релевантним контентом.</li><br><li><strong class="text-white">Економія бюджету (Cost Savings):</strong> Агенція повністю зекономила бюджет на базових послугах SMM-ника та копірайтера.</li><br><li><strong class="text-white">Фактична точність (Grounded AI):</strong> Оскільки генерація тексту базується на результатах пошуку Firecrawl, бот не створює "галюцинацій", а публікує реальні новини, тренди та ціни, зібрані з інтернету.</li><br></ul><br><br>---</div>
`
        }
    },
    {
        id: "proj_10",
        image: "assets/voice_banner.png",
        title: {
            en: `Ultra-Fast AI Voice Translator`,
            ua: `Ultra-Fast AI Voice Translator`
        },
        tags: ['n8n', 'Python', 'gRPC', 'OpenAI'],
        summary: {
            en: `A reliable simultaneous translation tool was needed for conducting negotiations and passing technical interviews with English-speaking companies. The initial architecture was assem...`,
            ua: `Для ведення переговорів та проходження технічних співбесід з англомовними компаніями був потрібен надійний інструмент синхронного перекладу. Початкова архітектура була зібрана в n8...`
        },
        content: {
            en: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. The business problem (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">A reliable simultaneous translation tool was needed for conducting negotiations and passing technical interviews with English-speaking companies. The initial architecture was assembled in n8n (Webhook -> STT -> LLM -> TTS). However, it had two critical flaws:<br>1.<strong class="text-white">Latency:</strong>Running nodes and routing data through n8n added extra seconds to processing. In a live dialogue, even a 1-2 second pause causes the interlocutor to lose focus.<br>2.<strong class="text-white">API Limitations:</strong>Quality voiceover models (eg OpenAI TTS) are paid. At the same time, NVIDIA offers phenomenal models (Riva) for free, but they do not support a standard REST API for easy integration into n8n, requiring operation via the gRPC protocol.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. The Solution and Architecture (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">In order to achieve maximum speed (Real-time), I abandoned n8n and wrote (via the AI ​​Vibecoding methodology) a custom multi-threaded application in pure Python. <br><br>The system works in two parallel streams:<br>-<strong class="text-white">My Voice (UA -> EN):</strong>Python script captures sound from the microphone using mathematical voice detection (Custom VAD via RMS Threshold). The audio is instantly transcribed via<strong class="text-white">Groq (Whisper v3)</strong>, translated by the<strong class="text-white">Llama 3.1 70B</strong>model, and voiced to my interlocutor via the high-speed<strong class="text-white">gRPC channels of NVIDIA Riva</strong>.<br>-<strong class="text-white">Voice of interlocutor (EN -> UA):</strong>Instead of spending precious milliseconds to generate a Ukrainian voice, the script "listens" to the system speakers (of the interlocutor), uses<strong class="text-white">Streaming STT</strong>from NVIDIA for on-the-fly recognition, translates the text and instantly displays it on my screen in the form of subtitles via a local web server on<strong class="text-white">Flask + SocketIO</strong>.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Tech Stack</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Foundation:</strong>Python (Threading, Queues)<br>-<strong class="text-white">Audio Engineering:</strong>\`sounddevice\`, \`numpy\`, Custom VAD logic (Voice Activity Detection)<br>-<strong class="text-white">AI models:</strong>Groq (Whisper-large-v3), NVIDIA Llama 3.1-70B-Instruct, NVIDIA Riva (ASR and TTS)<br>-<strong class="text-white">Communication protocols:</strong>gRPC (to minimize latency with NVIDIA), WebSockets (SocketIO)<br>-<strong class="text-white">UI/Interface:</strong>Local Flask Web Server (for live subtitles)</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Business result (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">-<strong class="text-white">Record speed (Low Latency):</strong>Abandoning visual programming in favor of gRPC and clean code saved the critical 1+ second on each phrase. This makes synchronous dialogue comfortable for both parties.<br>-<strong class="text-white">Total cost optimization:</strong>Using NVIDIA Riva's grant/free models instead of OpenAI's paid APIs made it possible to make hours of simultaneous translation absolutely free.<br>-<strong class="text-white">Seamless integration:</strong>The application can capture audio directly from system channels (Zoom, Google Meet, Slack Huddles), ensuring universality of work on any platform.<br><br><br>---</div>
`,
            ua: `<h3 class="text-xl font-bold mt-8 mb-3 text-accent">1. Проблема бізнесу (The Challenge)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Для ведення переговорів та проходження технічних співбесід з англомовними компаніями був потрібен надійний інструмент синхронного перекладу. Початкова архітектура була зібрана в n8n (Webhook -> STT -> LLM -> TTS). Проте вона мала два критичні недоліки:<br>1. <strong class="text-white">Latency (Затримка):</strong> Виконання нодів та маршрутизація даних через n8n додавали зайві секунди до обробки. У живому діалозі навіть 1-2 секунди паузи призводять до того, що співрозмовник втрачає фокус.<br>2. <strong class="text-white">Обмеження API:</strong> Якісні моделі озвучки (наприклад, OpenAI TTS) є платними. Водночас NVIDIA пропонує феноменальні моделі (Riva) безкоштовно, але вони не підтримують стандартний REST API для легкої інтеграції в n8n, вимагаючи роботи через протокол gRPC.</div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">2. Рішення та Архітектура (The Solution)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base">Щоб досягти максимальної швидкості (Real-time), я відмовився від n8n і написав (через методологію AI Vibecoding) кастомний багатопотоковий (Multi-threaded) застосунок на чистому Python. <br><br>Система працює у два паралельні потоки:<br><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Мій голос (UA -> EN):</strong> Python-скрипт захоплює звук з мікрофона, використовуючи математичну детекцію голосу (Custom VAD через RMS Threshold). Аудіо миттєво транскрибується через <strong class="text-white">Groq (Whisper v3)</strong>, перекладається моделлю <strong class="text-white">Llama 3.1 70B</strong> та озвучується для мого співрозмовника через швидкісні <strong class="text-white">gRPC-канали NVIDIA Riva</strong>.</li><br><li><strong class="text-white">Голос співрозмовника (EN -> UA):</strong> Замість того, щоб витрачати дорогоцінні мілісекунди на генерацію українського голосу, скрипт "слухає" системні динаміки (співрозмовника), використовує <strong class="text-white">Streaming STT</strong> від NVIDIA для розпізнавання на льоту, перекладає текст і миттєво виводить його мені на екран у вигляді субтитрів через локальний веб-сервер на <strong class="text-white">Flask + SocketIO</strong>.</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">3. Технічний стек (Tech Stack)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Основа:</strong> Python (Threading, Queues)</li><br><li><strong class="text-white">Audio Engineering:</strong> \`sounddevice\`, \`numpy\`, Custom VAD logic (Voice Activity Detection)</li><br><li><strong class="text-white">ШІ-моделі:</strong> Groq (Whisper-large-v3), NVIDIA Llama 3.1-70B-Instruct, NVIDIA Riva (ASR та TTS)</li><br><li><strong class="text-white">Протоколи зв'язку:</strong> gRPC (для мінімізації затримок з NVIDIA), WebSockets (SocketIO)</li><br><li><strong class="text-white">UI/Інтерфейс:</strong> Local Flask Web Server (для субтитрів у реальному часі)</li></ul></div>
<h3 class="text-xl font-bold mt-8 mb-3 text-accent">4. Бізнес-результат (Business Impact)</h3>
<div class="text-gray-300 leading-relaxed text-sm md:text-base"><ul class="list-disc pl-5 my-2 space-y-1"><li><strong class="text-white">Рекордна швидкість (Low Latency):</strong> Відмова від візуального програмування на користь gRPC та чистого коду дозволила зберегти критично важливу 1+ секунду на кожній фразі. Це робить синхронний діалог комфортним для обох сторін.</li><br><li><strong class="text-white">Тотальна оптимізація витрат:</strong> Використання грантових/безкоштовних моделей NVIDIA Riva замість платних API від OpenAI дозволило зробити години синхронного перекладу абсолютно безкоштовними.</li><br><li><strong class="text-white">Безшовна інтеграція:</strong> Застосунок вміє перехоплювати аудіо напряму із системних каналів (Zoom, Google Meet, Slack Huddles), забезпечуючи універсальність роботи на будь-якій платформі.</li><br></ul><br><br>---</div>
`
        }
    },
];
